["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
ERC721ex02 = [
    "/home/nadai/Nadai Cairo-721 Starknet Edu/contracts/Solución/ERC721ex02.cairo",
]
